'use client';

import React, { useState, useRef, useEffect } from 'react';
import { AdminLayout } from '@/components/layout/AdminLayout';
import { useEmsStore } from '@/store/emsStore';
import { useAuthStore } from '@/store/authStore';
import {
  Building2,
  Clock,
  CalendarDays,
  CreditCard,
  Bell,
  Save,
  CheckCircle2,
  AlertCircle,
  User,
  Camera,
  ShieldCheck,
  Upload,
  Trash2,
  Loader2,
  FileImage,
  RefreshCw,
  Info,
  Check,
  X,
  AlertTriangle,
  ExternalLink,
} from 'lucide-react';

const DEFAULT_AVATAR =
  'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&auto=format&fit=crop&q=80';
const MAX_FILE_SIZE = 5 * 1024 * 1024; // 5 MB
const ALLOWED_TYPES = ['image/jpeg', 'image/jpg', 'image/png', 'image/webp'];

export default function SettingsPage() {
  const { updateAdminProfile } = useEmsStore();
  const { updateUserAvatar } = useAuthStore();

  const [activeTab, setActiveTab] = useState<
    'profile' | 'org' | 'attendance' | 'leave' | 'payroll' | 'notification'
  >('profile');

  // Loading and Error states
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [toast, setToast] = useState<{ message: string; type: 'success' | 'error' } | null>(null);

  // Dirty State / Unsaved changes tracking
  const [isDirty, setIsDirty] = useState(false);
  const [pendingTab, setPendingTab] = useState<string | null>(null);
  const [showUnsavedModal, setShowUnsavedModal] = useState(false);

  // 1. Profile State
  const [profileData, setProfileData] = useState({
    userId: '',
    fullName: '',
    email: '',
    roleTitle: '',
    phone: '',
    avatar: DEFAULT_AVATAR,
    role: 'ADMIN',
    profilePhotoId: '',
  });

  // Photo Upload state
  const fileInputRef = useRef<HTMLInputElement>(null);
  const logoInputRef = useRef<HTMLInputElement>(null);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [currentGridFsId, setCurrentGridFsId] = useState<string | null>(null);

  // 2. Organization State
  const [orgData, setOrgData] = useState({
    name: '',
    legalName: '',
    code: '',
    industry: '',
    companyEmail: '',
    phone: '',
    website: '',
    address: '',
    city: '',
    state: '',
    country: '',
    postalCode: '',
    timezone: 'Asia/Kolkata',
    currency: 'INR',
    dateFormat: 'DD/MM/YYYY',
    logoUrl: '',
    logoFileId: '',
  });
  const [selectedLogoFile, setSelectedLogoFile] = useState<File | null>(null);
  const [logoPreviewUrl, setLogoPreviewUrl] = useState<string | null>(null);

  // 3. Attendance Rules State
  const [attendanceData, setAttendanceData] = useState({
    workStartTime: '09:00 AM',
    workEndTime: '06:00 PM',
    gracePeriodMinutes: 15,
    lateMarkingEnabled: true,
    halfDayThresholdHours: 4,
    minHoursFullDay: 8,
    overtimeEnabled: true,
    overtimeMinMinutes: 60,
    workingDaysPerWeek: 5,
    autoCheckoutEnabled: false,
    autoCheckoutTime: '11:59 PM',
    attendanceMethod: 'WEB_BIOMETRIC',
  });

  // 4. Leave Policies State
  const [leaveData, setLeaveData] = useState({
    approvalWorkflow: 'TWO_TIER',
    maxCarryForwardDays: 30,
    allowEncashment: true,
    halfDayAllowed: true,
    attachmentRequiredDays: 3,
    noticePeriodDays: 2,
    leaveTypes: [
      { id: 'casual', name: 'Casual Leave', code: 'CL', allowanceDays: 12, paid: true, carryForwardAllowed: false },
      { id: 'sick', name: 'Sick Leave', code: 'SL', allowanceDays: 10, paid: true, carryForwardAllowed: false },
      { id: 'earned', name: 'Earned Leave', code: 'EL', allowanceDays: 15, paid: true, carryForwardAllowed: true },
      { id: 'unpaid', name: 'Unpaid Leave / LOP', code: 'LOP', allowanceDays: 30, paid: false, carryForwardAllowed: false },
    ],
  });

  // 5. Payroll Settings State
  const [payrollData, setPayrollData] = useState({
    frequency: 'MONTHLY',
    processingDay: 1,
    currency: 'INR',
    workingDaysPerMonth: 26,
    lopCalculationMode: 'PRO_RATA_WORKING',
    overtimeRateMultiplier: 1.5,
    pfContributionPercent: 12.0,
    esiContributionPercent: 0.75,
    requireApproval: true,
    taxDeductionEnabled: true,
    payslipNote: 'Confidential payslip generated by Infinitive Cloud EMS.',
  });

  // 6. Notification Settings State
  const [notificationData, setNotificationData] = useState<{
    retentionDays: string;
    channelHealth: Record<string, { status: string; label: string; configurable: boolean }>;
    preferences: Array<{
      eventKey: string;
      eventName: string;
      category: string;
      channels: string[];
    }>;
  }>({
    retentionDays: '90',
    channelHealth: {
      IN_APP: { status: 'CONNECTED', label: 'In-App Notifications', configurable: true },
      EMAIL: { status: 'NOT_CONFIGURED', label: 'Email / SMTP Gateway', configurable: false },
      WHATSAPP: { status: 'NOT_CONFIGURED', label: 'WhatsApp Business API', configurable: false },
      SMS: { status: 'NOT_CONFIGURED', label: 'SMS Gateway', configurable: false },
    },
    preferences: [],
  });

  const showToast = (message: string, type: 'success' | 'error' = 'success') => {
    setToast({ message, type });
    setTimeout(() => setToast(null), 5000);
  };

  // Fetch all initial setting data from MongoDB APIs
  const fetchAllSettings = async () => {
    setIsLoading(true);
    setFetchError(null);

    try {
      const [profRes, orgRes, attRes, leaveRes, payRes, notifRes] = await Promise.all([
        fetch('/api/v1/settings/profile'),
        fetch('/api/v1/settings/organization'),
        fetch('/api/v1/settings/attendance'),
        fetch('/api/v1/settings/leave'),
        fetch('/api/v1/settings/payroll'),
        fetch('/api/v1/settings/notifications'),
      ]);

      const [profJson, orgJson, attJson, leaveJson, payJson, notifJson] = await Promise.all([
        profRes.json(),
        orgRes.json(),
        attRes.json(),
        leaveRes.json(),
        payRes.json(),
        notifRes.json(),
      ]);

      if (profJson.success && profJson.data) {
        setProfileData(profJson.data);
        if (profJson.data.profilePhotoId) {
          setCurrentGridFsId(profJson.data.profilePhotoId);
        }
      }

      if (orgJson.success && orgJson.data) {
        setOrgData(orgJson.data);
      }

      if (attJson.success && attJson.data) {
        setAttendanceData(attJson.data);
      }

      if (leaveJson.success && leaveJson.data) {
        setLeaveData(leaveJson.data);
      }

      if (payJson.success && payJson.data) {
        setPayrollData(payJson.data);
      }

      if (notifJson.success && notifJson.data) {
        setNotificationData(notifJson.data);
      }

      setIsDirty(false);
    } catch (err: any) {
      console.error('Error fetching settings:', err);
      setFetchError(err.message || 'Failed to load system settings from database.');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAllSettings();
  }, []);

  // Handle Tab Change with Unsaved Changes Guard
  const handleTabChange = (newTab: any) => {
    if (isDirty) {
      setPendingTab(newTab);
      setShowUnsavedModal(true);
    } else {
      setActiveTab(newTab);
    }
  };

  const confirmTabSwitch = () => {
    if (pendingTab) {
      setActiveTab(pendingTab as any);
      setPendingTab(null);
      setIsDirty(false);
      setSelectedFile(null);
      setPreviewUrl(null);
      setSelectedLogoFile(null);
      setLogoPreviewUrl(null);
    }
    setShowUnsavedModal(false);
  };

  // Handle Local File Pick for Profile Photo
  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (!ALLOWED_TYPES.includes(file.type.toLowerCase())) {
      showToast('Invalid file format. Only JPG, JPEG, PNG, and WEBP images are supported.', 'error');
      return;
    }

    if (file.size > MAX_FILE_SIZE) {
      const sizeMb = (file.size / (1024 * 1024)).toFixed(2);
      showToast(`Selected file size (${sizeMb} MB) exceeds the 5 MB limit.`, 'error');
      return;
    }

    setSelectedFile(file);
    const objectUrl = URL.createObjectURL(file);
    setPreviewUrl(objectUrl);
    setIsDirty(true);
    showToast(`Selected "${file.name}" (${(file.size / 1024).toFixed(1)} KB). Click Save to upload to GridFS.`, 'success');
  };

  // Handle Local File Pick for Organization Logo
  const handleLogoSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.size > MAX_FILE_SIZE) {
      showToast('Logo file size exceeds the 5 MB limit.', 'error');
      return;
    }

    setSelectedLogoFile(file);
    const objectUrl = URL.createObjectURL(file);
    setLogoPreviewUrl(objectUrl);
    setIsDirty(true);
    showToast(`Selected logo "${file.name}". Click Save Settings to upload.`, 'success');
  };

  // Save Profile & Photo
  const handleSaveProfile = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setIsSaving(true);

    try {
      let finalAvatarUrl = profileData.avatar;

      // 1. Upload photo to GridFS if new file selected
      if (selectedFile) {
        const formData = new FormData();
        formData.append('file', selectedFile);
        if (currentGridFsId) {
          formData.append('previousFileId', currentGridFsId);
        }

        const photoRes = await fetch('/api/v1/settings/profile/photo', {
          method: 'POST',
          body: formData,
        });

        const photoJson = await photoRes.json();
        if (!photoRes.ok || !photoJson.success) {
          throw new Error(photoJson.message || 'Failed to upload photo to MongoDB GridFS');
        }

        finalAvatarUrl = photoJson.photoUrl;
        if (photoJson.fileId) {
          setCurrentGridFsId(photoJson.fileId);
        }
        setSelectedFile(null);
        setPreviewUrl(null);
      }

      // 2. Save Profile fields to MongoDB
      const res = await fetch('/api/v1/settings/profile', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          fullName: profileData.fullName,
          roleTitle: profileData.roleTitle,
          phone: profileData.phone,
        }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Failed to update admin profile.');
      }

      const updatedProfile = {
        ...profileData,
        fullName: data.data.fullName,
        roleTitle: data.data.roleTitle,
        phone: data.data.phone,
        avatar: finalAvatarUrl,
      };

      setProfileData(updatedProfile);
      updateAdminProfile({
        name: data.data.fullName,
        email: profileData.email,
        role: data.data.roleTitle,
        avatar: finalAvatarUrl,
        phone: data.data.phone,
      });
      updateUserAvatar(finalAvatarUrl);

      setIsDirty(false);
      showToast('Admin Profile & Photo saved to MongoDB GridFS successfully!', 'success');
    } catch (err: any) {
      console.error('Error saving profile:', err);
      showToast(err.message || 'Failed to save profile.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // Remove Photo from GridFS
  const handleRemovePhoto = async () => {
    setIsSaving(true);
    try {
      let url = '/api/v1/settings/profile/photo';
      if (currentGridFsId) {
        url += `?id=${currentGridFsId}`;
      }

      const res = await fetch(url, { method: 'DELETE' });
      const data = await res.json();

      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Failed to delete photo from GridFS.');
      }

      const newAvatar = data.defaultAvatar || DEFAULT_AVATAR;

      setSelectedFile(null);
      setPreviewUrl(null);
      setCurrentGridFsId(null);

      const updatedProfile = {
        ...profileData,
        avatar: newAvatar,
        profilePhotoId: '',
      };

      setProfileData(updatedProfile);
      updateAdminProfile({
        name: profileData.fullName,
        email: profileData.email,
        role: profileData.roleTitle,
        avatar: newAvatar,
        phone: profileData.phone,
      });
      updateUserAvatar(newAvatar);

      setIsDirty(false);
      showToast('Profile photo removed from GridFS successfully!', 'success');
    } catch (err: any) {
      showToast(err.message || 'Failed to delete photo.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // Save Organization Settings
  const handleSaveOrg = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setIsSaving(true);

    try {
      // Upload logo if selected
      let logoUrl = orgData.logoUrl;
      if (selectedLogoFile) {
        const formData = new FormData();
        formData.append('file', selectedLogoFile);
        const logoRes = await fetch('/api/v1/settings/organization/logo', {
          method: 'POST',
          body: formData,
        });
        const logoJson = await logoRes.json();
        if (!logoRes.ok || !logoJson.success) {
          throw new Error(logoJson.message || 'Failed to upload organization logo.');
        }
        logoUrl = logoJson.logoUrl;
        setSelectedLogoFile(null);
        setLogoPreviewUrl(null);
      }

      const res = await fetch('/api/v1/settings/organization', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...orgData, logoUrl }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Failed to save organization settings.');
      }

      setOrgData(data.data);
      setIsDirty(false);
      showToast('Organization settings persisted to MongoDB successfully!', 'success');
    } catch (err: any) {
      showToast(err.message || 'Failed to save organization settings.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // Save Attendance Settings
  const handleSaveAttendance = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setIsSaving(true);

    try {
      const res = await fetch('/api/v1/settings/attendance', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(attendanceData),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Failed to save attendance rules.');
      }

      setAttendanceData(data.data);
      setIsDirty(false);
      showToast('Attendance rules saved and applied to attendance calculations!', 'success');
    } catch (err: any) {
      showToast(err.message || 'Failed to save attendance rules.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // Save Leave Settings
  const handleSaveLeave = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setIsSaving(true);

    try {
      const res = await fetch('/api/v1/settings/leave', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(leaveData),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Failed to save leave policies.');
      }

      setLeaveData(data.data);
      setIsDirty(false);
      showToast('Leave policies saved successfully!', 'success');
    } catch (err: any) {
      showToast(err.message || 'Failed to save leave policies.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // Save Payroll Settings
  const handleSavePayroll = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setIsSaving(true);

    try {
      const res = await fetch('/api/v1/settings/payroll', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payrollData),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Failed to save payroll settings.');
      }

      setPayrollData(data.data);
      setIsDirty(false);
      showToast('Payroll settings saved successfully!', 'success');
    } catch (err: any) {
      showToast(err.message || 'Failed to save payroll settings.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // Save Notification Settings
  const handleSaveNotifications = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    setIsSaving(true);

    try {
      const res = await fetch('/api/v1/settings/notifications', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          retentionDays: notificationData.retentionDays,
          preferences: notificationData.preferences,
        }),
      });

      const data = await res.json();
      if (!res.ok || !data.success) {
        throw new Error(data.message || 'Failed to save notification settings.');
      }

      setIsDirty(false);
      showToast('Notification settings & event preferences updated!', 'success');
    } catch (err: any) {
      showToast(err.message || 'Failed to save notification settings.', 'error');
    } finally {
      setIsSaving(false);
    }
  };

  // Contextual Save Master Handler
  const handleSaveCurrentTab = () => {
    switch (activeTab) {
      case 'profile':
        return handleSaveProfile();
      case 'org':
        return handleSaveOrg();
      case 'attendance':
        return handleSaveAttendance();
      case 'leave':
        return handleSaveLeave();
      case 'payroll':
        return handleSavePayroll();
      case 'notification':
        return handleSaveNotifications();
    }
  };

  const displayAvatar = previewUrl || profileData.avatar || DEFAULT_AVATAR;
  const displayLogo = logoPreviewUrl || orgData.logoUrl;

  return (
    <AdminLayout
      pageTitle="System Settings & Executive Control Center"
      breadcrumbs={[{ label: 'Settings', href: '/admin/settings' }]}
    >
      {/* Toast Notification */}
      {toast && (
        <div
          className={`fixed right-6 top-20 z-50 flex items-center gap-2.5 rounded-xl px-4 py-3 text-xs text-white shadow-2xl border transition-all ${
            toast.type === 'success'
              ? 'bg-slate-900 border-emerald-500/50'
              : 'bg-rose-950 border-rose-500/50'
          }`}
        >
          {toast.type === 'success' ? (
            <CheckCircle2 className="h-4 w-4 text-emerald-400 shrink-0" />
          ) : (
            <AlertCircle className="h-4 w-4 text-rose-400 shrink-0" />
          )}
          <span className="font-medium">{toast.message}</span>
        </div>
      )}

      {/* Unsaved Changes Confirmation Modal */}
      {showUnsavedModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 backdrop-blur-sm p-4">
          <div className="w-full max-w-md rounded-2xl bg-white p-6 shadow-2xl border border-slate-200">
            <div className="flex items-center gap-3 text-amber-600 mb-3">
              <AlertTriangle className="h-6 w-6" />
              <h3 className="text-base font-bold text-slate-900">Unsaved Changes</h3>
            </div>
            <p className="text-xs text-slate-600 leading-relaxed mb-6">
              You have modified settings in the current tab that have not been saved to MongoDB. Navigating away will discard these changes.
            </p>
            <div className="flex justify-end gap-3">
              <button
                onClick={() => setShowUnsavedModal(false)}
                className="rounded-xl border border-slate-200 px-4 py-2 text-xs font-semibold text-slate-700 hover:bg-slate-100"
              >
                Stay & Edit
              </button>
              <button
                onClick={confirmTabSwitch}
                className="rounded-xl bg-rose-600 px-4 py-2 text-xs font-semibold text-white hover:bg-rose-700 shadow-sm"
              >
                Discard & Switch
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Header Bar */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-xl font-bold text-slate-900">System & Admin Settings</h2>
          <p className="text-xs text-slate-500">
            Manage admin profile, GridFS storage, organization details, attendance rules, leave policies, payroll parameters, and notifications.
          </p>
        </div>

        <div className="flex items-center gap-3">
          {isDirty && (
            <span className="hidden sm:inline-flex items-center gap-1.5 rounded-lg bg-amber-50 px-2.5 py-1 text-[11px] font-bold text-amber-700 border border-amber-200">
              <AlertTriangle className="h-3.5 w-3.5" /> Unsaved changes
            </span>
          )}

          <button
            onClick={handleSaveCurrentTab}
            disabled={isSaving || isLoading}
            className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white shadow-md hover:bg-blue-700 active:scale-95 disabled:opacity-50 transition-all"
          >
            {isSaving ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Save className="h-4 w-4" />
            )}
            <span>
              {isSaving
                ? 'Persisting to MongoDB...'
                : activeTab === 'profile'
                ? 'Save Profile & Photo'
                : 'Save Settings'}
            </span>
          </button>
        </div>
      </div>

      {/* Settings Navigation Bar */}
      <div className="flex border-b border-slate-200 bg-white rounded-xl p-1 shadow-sm text-xs font-semibold text-slate-600 overflow-x-auto">
        {[
          { key: 'profile', label: 'Admin Profile & Photo', icon: User },
          { key: 'org', label: 'Organization Settings', icon: Building2 },
          { key: 'attendance', label: 'Attendance Rules', icon: Clock },
          { key: 'leave', label: 'Leave Policies', icon: CalendarDays },
          { key: 'payroll', label: 'Payroll Settings', icon: CreditCard },
          { key: 'notification', label: 'Notification Settings', icon: Bell },
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.key;
          return (
            <button
              key={tab.key}
              onClick={() => handleTabChange(tab.key)}
              className={`flex items-center gap-2 rounded-lg px-4 py-2.5 transition-all whitespace-nowrap ${
                isActive
                  ? 'bg-blue-600 text-white shadow-sm font-bold'
                  : 'hover:bg-slate-100 hover:text-slate-900 font-medium'
              }`}
            >
              <Icon className="h-4 w-4" />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* Main Settings Content Area */}
      {isLoading ? (
        <div className="rounded-2xl border border-slate-200 bg-white p-12 shadow-sm text-center">
          <Loader2 className="h-8 w-8 animate-spin text-blue-600 mx-auto mb-3" />
          <p className="text-xs font-semibold text-slate-600">Loading system settings from MongoDB Atlas...</p>
        </div>
      ) : fetchError ? (
        <div className="rounded-2xl border border-rose-200 bg-rose-50/60 p-8 text-center text-rose-900">
          <AlertCircle className="h-8 w-8 text-rose-600 mx-auto mb-2" />
          <h3 className="text-sm font-bold">Failed to Load Settings</h3>
          <p className="text-xs text-rose-700 mt-1 mb-4">{fetchError}</p>
          <button
            onClick={fetchAllSettings}
            className="inline-flex items-center gap-2 rounded-xl bg-rose-600 px-4 py-2 text-xs font-bold text-white shadow-sm hover:bg-rose-700"
          >
            <RefreshCw className="h-4 w-4" /> Retry
          </button>
        </div>
      ) : (
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm text-xs text-slate-700">
          {/* TAB 1: ADMIN PROFILE & REAL PHOTO UPLOAD VIA MONGODB GRIDFS */}
          {activeTab === 'profile' && (
            <form onSubmit={handleSaveProfile} className="space-y-6">
              {/* Hidden File Input */}
              <input
                type="file"
                ref={fileInputRef}
                accept="image/jpeg,image/png,image/webp"
                onChange={handleFileSelect}
                className="hidden"
              />

              {/* Photo Section */}
              <div className="flex flex-col sm:flex-row items-center gap-6 border-b border-slate-100 pb-6">
                {/* Profile Image Preview */}
                <div className="relative h-28 w-28 flex-shrink-0 overflow-hidden rounded-full ring-4 ring-blue-500/20 shadow-lg group">
                  <img
                    src={displayAvatar}
                    alt={profileData.fullName}
                    className="h-28 w-28 rounded-full object-cover"
                  />
                  <div
                    onClick={() => fileInputRef.current?.click()}
                    className="absolute inset-0 bg-slate-900/40 flex flex-col items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer text-white"
                  >
                    <Camera className="h-6 w-6" />
                    <span className="text-[10px] font-bold mt-1">Change</span>
                  </div>
                </div>

                {/* Photo Actions & Metadata */}
                <div className="flex-1 space-y-3 text-center sm:text-left">
                  <div className="flex items-center justify-center sm:justify-start gap-2">
                    <h3 className="text-base font-bold text-slate-900">Admin Profile Photo</h3>
                    <span className="flex items-center gap-1 rounded-md bg-blue-50 px-2 py-0.5 text-[10px] font-bold text-blue-700 border border-blue-200">
                      <ShieldCheck className="h-3 w-3" /> MongoDB GridFS Storage
                    </span>
                  </div>

                  <p className="text-slate-500 text-xs leading-relaxed max-w-xl">
                    Upload an image file from your computer (JPG, PNG, WEBP; max 5 MB). The binary data will be stored directly in MongoDB GridFS (`photos` bucket).
                  </p>

                  {/* Selected File Details */}
                  {selectedFile && (
                    <div className="inline-flex items-center gap-2 rounded-xl border border-blue-200 bg-blue-50/60 px-3 py-1.5 text-xs text-blue-900 font-medium">
                      <FileImage className="h-4 w-4 text-blue-600" />
                      <span>
                        Selected: <strong>{selectedFile.name}</strong> ({(selectedFile.size / 1024).toFixed(1)} KB)
                      </span>
                      <span className="rounded bg-blue-200 px-1.5 py-0.5 text-[10px] uppercase font-bold text-blue-800">
                        {selectedFile.type.split('/')[1]}
                      </span>
                    </div>
                  )}

                  {/* Upload Buttons */}
                  <div className="flex flex-wrap items-center justify-center sm:justify-start gap-3 pt-1">
                    <button
                      type="button"
                      onClick={() => fileInputRef.current?.click()}
                      disabled={isSaving}
                      className="flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-2 font-semibold text-white hover:bg-slate-800 active:scale-95 transition-all shadow-sm disabled:opacity-50"
                    >
                      <Upload className="h-3.5 w-3.5 text-blue-400" />
                      <span>Select Image from Computer</span>
                    </button>

                    <button
                      type="button"
                      onClick={handleRemovePhoto}
                      disabled={isSaving}
                      className="flex items-center gap-1.5 rounded-xl border border-rose-200 bg-rose-50/60 px-3 py-2 font-semibold text-rose-700 hover:bg-rose-100 active:scale-95 transition-all disabled:opacity-50"
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                      <span>Remove Photo</span>
                    </button>
                  </div>
                </div>
              </div>

              {/* Form Fields Grid */}
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div>
                  <label className="font-bold text-slate-900">Admin Full Name *</label>
                  <input
                    type="text"
                    required
                    value={profileData.fullName}
                    onChange={(e) => {
                      setProfileData({ ...profileData, fullName: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 focus:border-blue-500 focus:bg-white font-semibold text-slate-900"
                  />
                </div>

                <div>
                  <label className="font-bold text-slate-900">Admin Email Address (Read Only)</label>
                  <input
                    type="email"
                    readOnly
                    value={profileData.email}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-100 font-semibold text-slate-600 cursor-not-allowed"
                  />
                  <p className="text-[10px] text-slate-400 mt-1">Primary email is bound to authentication identity and cannot be changed here.</p>
                </div>

                <div>
                  <label className="font-bold text-slate-900">Role Title / Designation</label>
                  <input
                    type="text"
                    value={profileData.roleTitle}
                    onChange={(e) => {
                      setProfileData({ ...profileData, roleTitle: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 focus:border-blue-500 focus:bg-white font-medium"
                  />
                </div>

                <div>
                  <label className="font-bold text-slate-900">Contact Phone</label>
                  <input
                    type="text"
                    value={profileData.phone}
                    onChange={(e) => {
                      setProfileData({ ...profileData, phone: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 focus:border-blue-500 focus:bg-white font-medium"
                  />
                </div>
              </div>

              <div className="flex justify-end border-t pt-4">
                <button
                  type="submit"
                  disabled={isSaving}
                  className="flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-2.5 font-bold text-white shadow-md hover:bg-blue-700 active:scale-95 disabled:opacity-50"
                >
                  {isSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                  <span>{isSaving ? 'Saving to MongoDB...' : 'Save Profile & Photo'}</span>
                </button>
              </div>
            </form>
          )}

          {/* TAB 2: ORGANIZATION SETTINGS */}
          {activeTab === 'org' && (
            <form onSubmit={handleSaveOrg} className="space-y-6">
              {/* Logo Section */}
              <div className="flex flex-col sm:flex-row items-center gap-6 border-b border-slate-100 pb-6">
                <input
                  type="file"
                  ref={logoInputRef}
                  accept="image/jpeg,image/png,image/webp,image/svg+xml"
                  onChange={handleLogoSelect}
                  className="hidden"
                />
                <div className="h-20 w-36 flex-shrink-0 border-2 border-dashed border-slate-300 rounded-xl bg-slate-50 flex items-center justify-center p-2 relative group overflow-hidden">
                  {displayLogo ? (
                    <img src={displayLogo} alt="Company Logo" className="max-h-full max-w-full object-contain" />
                  ) : (
                    <Building2 className="h-8 w-8 text-slate-400" />
                  )}
                  <div
                    onClick={() => logoInputRef.current?.click()}
                    className="absolute inset-0 bg-slate-900/50 flex items-center justify-center text-white opacity-0 group-hover:opacity-100 transition-opacity cursor-pointer font-bold text-[11px]"
                  >
                    Upload Logo
                  </div>
                </div>
                <div>
                  <h3 className="font-bold text-slate-900 text-sm">Company Branding & Logo</h3>
                  <p className="text-slate-500 text-xs mt-1">Upload company logo (PNG, SVG, JPG; max 5 MB). Stored in MongoDB GridFS.</p>
                  <button
                    type="button"
                    onClick={() => logoInputRef.current?.click()}
                    className="mt-2 text-xs text-blue-600 font-bold hover:underline"
                  >
                    Select Logo Image
                  </button>
                </div>
              </div>

              {/* Organization Info Grid */}
              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div>
                  <label className="font-bold text-slate-900">Organization Name *</label>
                  <input
                    type="text"
                    required
                    value={orgData.name}
                    onChange={(e) => {
                      setOrgData({ ...orgData, name: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-semibold"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-900">Legal Company Name</label>
                  <input
                    type="text"
                    value={orgData.legalName}
                    onChange={(e) => {
                      setOrgData({ ...orgData, legalName: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-900">Organization Code</label>
                  <input
                    type="text"
                    value={orgData.code}
                    onChange={(e) => {
                      setOrgData({ ...orgData, code: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-900">Industry Segment</label>
                  <input
                    type="text"
                    value={orgData.industry}
                    onChange={(e) => {
                      setOrgData({ ...orgData, industry: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-900">Company Email</label>
                  <input
                    type="email"
                    value={orgData.companyEmail}
                    onChange={(e) => {
                      setOrgData({ ...orgData, companyEmail: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-900">Company Phone</label>
                  <input
                    type="text"
                    value={orgData.phone}
                    onChange={(e) => {
                      setOrgData({ ...orgData, phone: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-900">Timezone</label>
                  <select
                    value={orgData.timezone}
                    onChange={(e) => {
                      setOrgData({ ...orgData, timezone: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  >
                    <option value="Asia/Kolkata">Asia/Kolkata (IST +5:30)</option>
                    <option value="America/New_York">America/New_York (EST)</option>
                    <option value="Europe/London">Europe/London (GMT/BST)</option>
                    <option value="Asia/Dubai">Asia/Dubai (GST)</option>
                  </select>
                </div>
                <div>
                  <label className="font-bold text-slate-900">Currency</label>
                  <select
                    value={orgData.currency}
                    onChange={(e) => {
                      setOrgData({ ...orgData, currency: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  >
                    <option value="INR">INR (₹)</option>
                    <option value="USD">USD ($)</option>
                    <option value="EUR">EUR (€)</option>
                    <option value="GBP">GBP (£)</option>
                  </select>
                </div>
              </div>

              <div className="flex justify-end border-t pt-4">
                <button
                  type="submit"
                  disabled={isSaving}
                  className="flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-2.5 font-bold text-white shadow-md hover:bg-blue-700 active:scale-95 disabled:opacity-50"
                >
                  {isSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                  <span>Save Organization Settings</span>
                </button>
              </div>
            </form>
          )}

          {/* TAB 3: ATTENDANCE RULES */}
          {activeTab === 'attendance' && (
            <form onSubmit={handleSaveAttendance} className="space-y-6">
              <div className="border-b border-slate-100 pb-4">
                <h3 className="font-bold text-slate-900 text-sm">Shift Timings & Calculation Engine Rules</h3>
                <p className="text-slate-500 text-xs">These parameters dynamically govern attendance late markings, half-day thresholds, and overtime calculations across the system.</p>
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div>
                  <label className="font-bold text-slate-900">Official Shift Start Time</label>
                  <input
                    type="text"
                    value={attendanceData.workStartTime}
                    onChange={(e) => {
                      setAttendanceData({ ...attendanceData, workStartTime: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                    placeholder="09:00 AM"
                  />
                </div>
                <div>
                  <label className="font-bold text-slate-900">Official Shift End Time</label>
                  <input
                    type="text"
                    value={attendanceData.workEndTime}
                    onChange={(e) => {
                      setAttendanceData({ ...attendanceData, workEndTime: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                    placeholder="06:00 PM"
                  />
                </div>

                <div>
                  <label className="font-bold text-slate-900">Late Mark Grace Period (Minutes)</label>
                  <input
                    type="number"
                    min="0"
                    max="180"
                    value={attendanceData.gracePeriodMinutes}
                    onChange={(e) => {
                      setAttendanceData({ ...attendanceData, gracePeriodMinutes: Number(e.target.value) });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                  <p className="text-[10px] text-slate-400 mt-1">Arrivals after Shift Start + Grace Period are automatically flagged as Late.</p>
                </div>

                <div>
                  <label className="font-bold text-slate-900">Half-Day Threshold (Hours)</label>
                  <input
                    type="number"
                    min="1"
                    max="12"
                    value={attendanceData.halfDayThresholdHours}
                    onChange={(e) => {
                      setAttendanceData({ ...attendanceData, halfDayThresholdHours: Number(e.target.value) });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>

                <div>
                  <label className="font-bold text-slate-900">Minimum Hours for Full Day</label>
                  <input
                    type="number"
                    min="1"
                    max="16"
                    value={attendanceData.minHoursFullDay}
                    onChange={(e) => {
                      setAttendanceData({ ...attendanceData, minHoursFullDay: Number(e.target.value) });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>

                <div>
                  <label className="font-bold text-slate-900">Working Days Per Week</label>
                  <select
                    value={attendanceData.workingDaysPerWeek}
                    onChange={(e) => {
                      setAttendanceData({ ...attendanceData, workingDaysPerWeek: Number(e.target.value) });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  >
                    <option value={5}>5 Days (Mon - Fri)</option>
                    <option value={6}>6 Days (Mon - Sat)</option>
                  </select>
                </div>
              </div>

              <div className="space-y-3 pt-2 border-t">
                <label className="flex items-center gap-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={attendanceData.lateMarkingEnabled}
                    onChange={(e) => {
                      setAttendanceData({ ...attendanceData, lateMarkingEnabled: e.target.checked });
                      setIsDirty(true);
                    }}
                    className="h-4 w-4 text-blue-600 rounded"
                  />
                  <span className="font-bold text-slate-900">Enable Automatic Late Arrival Marking</span>
                </label>

                <label className="flex items-center gap-3 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={attendanceData.overtimeEnabled}
                    onChange={(e) => {
                      setAttendanceData({ ...attendanceData, overtimeEnabled: e.target.checked });
                      setIsDirty(true);
                    }}
                    className="h-4 w-4 text-blue-600 rounded"
                  />
                  <span className="font-bold text-slate-900">Enable Overtime Tracking</span>
                </label>
              </div>

              <div className="flex justify-end border-t pt-4">
                <button
                  type="submit"
                  disabled={isSaving}
                  className="flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-2.5 font-bold text-white shadow-md hover:bg-blue-700 active:scale-95 disabled:opacity-50"
                >
                  {isSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                  <span>Save Attendance Rules</span>
                </button>
              </div>
            </form>
          )}

          {/* TAB 4: LEAVE POLICIES */}
          {activeTab === 'leave' && (
            <form onSubmit={handleSaveLeave} className="space-y-6">
              <div className="border-b border-slate-100 pb-4">
                <h3 className="font-bold text-slate-900 text-sm">Leave Allocation & Approval Policies</h3>
                <p className="text-slate-500 text-xs">Configure notice requirements, carry-forward caps, and approval workflows for leave requests.</p>
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div>
                  <label className="font-bold text-slate-900">Approval Workflow Tier</label>
                  <select
                    value={leaveData.approvalWorkflow}
                    onChange={(e) => {
                      setLeaveData({ ...leaveData, approvalWorkflow: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  >
                    <option value="SINGLE_TIER">Single Tier (HR Only)</option>
                    <option value="TWO_TIER">2-Tier (Manager → HR Approval)</option>
                  </select>
                </div>

                <div>
                  <label className="font-bold text-slate-900">Max Carry-Forward Limit (Days / Year)</label>
                  <input
                    type="number"
                    min="0"
                    max="365"
                    value={leaveData.maxCarryForwardDays}
                    onChange={(e) => {
                      setLeaveData({ ...leaveData, maxCarryForwardDays: Number(e.target.value) });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>

                <div>
                  <label className="font-bold text-slate-900">Advance Notice Requirement (Days)</label>
                  <input
                    type="number"
                    min="0"
                    max="30"
                    value={leaveData.noticePeriodDays}
                    onChange={(e) => {
                      setLeaveData({ ...leaveData, noticePeriodDays: Number(e.target.value) });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                  <p className="text-[10px] text-slate-400 mt-1">Employees must apply at least X days in advance for planned leaves.</p>
                </div>

                <div>
                  <label className="font-bold text-slate-900">Medical Certificate Required If Duration ≥ (Days)</label>
                  <input
                    type="number"
                    min="1"
                    max="30"
                    value={leaveData.attachmentRequiredDays}
                    onChange={(e) => {
                      setLeaveData({ ...leaveData, attachmentRequiredDays: Number(e.target.value) });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>
              </div>

              {/* Configured Leave Types List */}
              <div className="space-y-3 border-t pt-4">
                <h4 className="font-bold text-slate-900 text-xs">Standard Leave Category Allowances</h4>
                <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                  {leaveData.leaveTypes.map((lt, idx) => (
                    <div key={lt.id || idx} className="flex items-center justify-between rounded-xl border p-3 bg-slate-50">
                      <div>
                        <span className="font-bold text-slate-900">{lt.name}</span>
                        <span className="ml-2 text-[10px] bg-slate-200 px-1.5 py-0.5 rounded font-mono font-bold text-slate-700">{lt.code}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <span className="text-xs text-slate-500 font-medium">Allowance:</span>
                        <input
                          type="number"
                          min="0"
                          value={lt.allowanceDays}
                          onChange={(e) => {
                            const newTypes = [...leaveData.leaveTypes];
                            newTypes[idx].allowanceDays = Number(e.target.value);
                            setLeaveData({ ...leaveData, leaveTypes: newTypes });
                            setIsDirty(true);
                          }}
                          className="w-16 rounded-lg border p-1 bg-white font-bold text-center text-xs"
                        />
                        <span className="text-xs text-slate-500 font-medium">Days</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex justify-end border-t pt-4">
                <button
                  type="submit"
                  disabled={isSaving}
                  className="flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-2.5 font-bold text-white shadow-md hover:bg-blue-700 active:scale-95 disabled:opacity-50"
                >
                  {isSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                  <span>Save Leave Policies</span>
                </button>
              </div>
            </form>
          )}

          {/* TAB 5: PAYROLL SETTINGS */}
          {activeTab === 'payroll' && (
            <form onSubmit={handleSavePayroll} className="space-y-6">
              <div className="border-b border-slate-100 pb-4">
                <h3 className="font-bold text-slate-900 text-sm">Payroll Cycle & Formula Configurations</h3>
                <p className="text-slate-500 text-xs">Manage organizational LOP modes, working days, Statutory PF/ESI %, and overtime multipliers.</p>
              </div>

              <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
                <div>
                  <label className="font-bold text-slate-900">Payroll Cycle Frequency</label>
                  <select
                    value={payrollData.frequency}
                    onChange={(e) => {
                      setPayrollData({ ...payrollData, frequency: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  >
                    <option value="MONTHLY">Monthly (1st to Last Day)</option>
                    <option value="BI_WEEKLY">Bi-Weekly</option>
                  </select>
                </div>

                <div>
                  <label className="font-bold text-slate-900">Disbursement / Processing Day of Month</label>
                  <input
                    type="number"
                    min="1"
                    max="28"
                    value={payrollData.processingDay}
                    onChange={(e) => {
                      setPayrollData({ ...payrollData, processingDay: Number(e.target.value) });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>

                <div>
                  <label className="font-bold text-slate-900">Working Days Per Month (For LOP Calculation)</label>
                  <select
                    value={payrollData.workingDaysPerMonth}
                    onChange={(e) => {
                      setPayrollData({ ...payrollData, workingDaysPerMonth: e.target.value === 'ACTUAL' ? 'ACTUAL' : Number(e.target.value) as any });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  >
                    <option value={26}>Fixed 26 Working Days</option>
                    <option value={30}>Fixed 30 Calendar Days</option>
                    <option value="ACTUAL">Actual Days in Current Month</option>
                  </select>
                </div>

                <div>
                  <label className="font-bold text-slate-900">LOP Deduction Mode</label>
                  <select
                    value={payrollData.lopCalculationMode}
                    onChange={(e) => {
                      setPayrollData({ ...payrollData, lopCalculationMode: e.target.value });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  >
                    <option value="PRO_RATA_WORKING">Pro-Rata Working Days Deduction</option>
                    <option value="PRO_RATA_CALENDAR">Pro-Rata Calendar Days Deduction</option>
                  </select>
                </div>

                <div>
                  <label className="font-bold text-slate-900">PF Contribution Rate (% of Basic)</label>
                  <input
                    type="number"
                    step="0.1"
                    min="0"
                    max="50"
                    value={payrollData.pfContributionPercent}
                    onChange={(e) => {
                      setPayrollData({ ...payrollData, pfContributionPercent: Number(e.target.value) });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>

                <div>
                  <label className="font-bold text-slate-900">ESI Contribution Rate (% of Gross)</label>
                  <input
                    type="number"
                    step="0.05"
                    min="0"
                    max="20"
                    value={payrollData.esiContributionPercent}
                    onChange={(e) => {
                      setPayrollData({ ...payrollData, esiContributionPercent: Number(e.target.value) });
                      setIsDirty(true);
                    }}
                    className="mt-1 w-full rounded-xl border p-2.5 bg-slate-50 font-medium"
                  />
                </div>
              </div>

              <div className="flex justify-end border-t pt-4">
                <button
                  type="submit"
                  disabled={isSaving}
                  className="flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-2.5 font-bold text-white shadow-md hover:bg-blue-700 active:scale-95 disabled:opacity-50"
                >
                  {isSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                  <span>Save Payroll Settings</span>
                </button>
              </div>
            </form>
          )}

          {/* TAB 6: NOTIFICATION SETTINGS */}
          {activeTab === 'notification' && (
            <form onSubmit={handleSaveNotifications} className="space-y-6">
              <div className="border-b border-slate-100 pb-4">
                <h3 className="font-bold text-slate-900 text-sm">Notification Channels & Delivery Preferences</h3>
                <p className="text-slate-500 text-xs">Verify channel readiness from `/admin/integrations` and configure system event preferences.</p>
              </div>

              {/* Delivery Channels Health Status Banner */}
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-4">
                {Object.entries(notificationData.channelHealth || {}).map(([key, ch]) => (
                  <div
                    key={key}
                    className={`rounded-xl border p-3 flex flex-col justify-between ${
                      ch.status === 'CONNECTED'
                        ? 'border-emerald-200 bg-emerald-50/50 text-emerald-900'
                        : 'border-amber-200 bg-amber-50/50 text-amber-900'
                    }`}
                  >
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-xs">{ch.label}</span>
                      {ch.status === 'CONNECTED' ? (
                        <CheckCircle2 className="h-4 w-4 text-emerald-600" />
                      ) : (
                        <AlertCircle className="h-4 w-4 text-amber-600" />
                      )}
                    </div>
                    <span className="text-[10px] font-bold mt-2 uppercase">
                      Status: {ch.status}
                    </span>
                  </div>
                ))}
              </div>

              {/* Retention Policy */}
              <div>
                <label className="font-bold text-slate-900">Notification Retention Policy</label>
                <select
                  value={notificationData.retentionDays}
                  onChange={(e) => {
                    setNotificationData({ ...notificationData, retentionDays: e.target.value });
                    setIsDirty(true);
                  }}
                  className="mt-1 w-full max-w-xs rounded-xl border p-2.5 bg-slate-50 font-medium"
                >
                  <option value="30">Keep for 30 Days</option>
                  <option value="60">Keep for 60 Days</option>
                  <option value="90">Keep for 90 Days</option>
                  <option value="365">Keep for 1 Year</option>
                  <option value="INDEFINITE">Keep Indefinitely</option>
                </select>
              </div>

              <div className="flex justify-end border-t pt-4">
                <button
                  type="submit"
                  disabled={isSaving}
                  className="flex items-center gap-2 rounded-xl bg-blue-600 px-6 py-2.5 font-bold text-white shadow-md hover:bg-blue-700 active:scale-95 disabled:opacity-50"
                >
                  {isSaving ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                  <span>Save Notification Preferences</span>
                </button>
              </div>
            </form>
          )}
        </div>
      )}
    </AdminLayout>
  );
}
