import { NextRequest, NextResponse } from 'next/server';
import { connectToDatabase } from '@/lib/mongodb';
import { getAuthContext, checkPermissions } from '@/lib/auth';
import { logAuditEvent } from '@/lib/audit';

export const dynamic = 'force-dynamic';

const DEFAULT_PAYROLL_SETTINGS = {
  frequency: 'MONTHLY',
  processingDay: 1,
  currency: 'INR',
  workingDaysPerMonth: 26,
  lopCalculationMode: 'PRO_RATA_WORKING',
  overtimeRateMultiplier: 1.5,
  pfContributionPercent: 12.0,
  esiContributionPercent: 0.75,
  requireApproval: true,
  taxDeductionEnabled: true,
  payslipNote: 'Confidential payslip generated by Infinitive Cloud EMS.',
};

// GET /api/v1/settings/payroll - Fetch organization payroll settings
export async function GET(req: NextRequest) {
  try {
    const auth = getAuthContext(req);
    const perm = checkPermissions(auth);
    if (!perm.isAllowed) {
      return NextResponse.json(
        { success: false, message: perm.message },
        { status: perm.statusCode }
      );
    }

    const { db } = await connectToDatabase();
    const orgId = auth.organizationId;

    let orgDoc: any = await db.collection('organization_settings').findOne({ organizationId: orgId });

    if (!orgDoc || !orgDoc.payroll) {
      await db.collection('organization_settings').updateOne(
        { organizationId: orgId },
        { $set: { payroll: DEFAULT_PAYROLL_SETTINGS, updatedAt: new Date() } },
        { upsert: true }
      );
    }

    return NextResponse.json({
      success: true,
      data: {
        organizationId: orgId,
        ...DEFAULT_PAYROLL_SETTINGS,
        ...(orgDoc?.payroll || {}),
      },
    });
  } catch (error: any) {
    console.error('Error in GET /api/v1/settings/payroll:', error);
    return NextResponse.json(
      { success: false, message: error.message || 'Failed to fetch payroll settings.' },
      { status: 500 }
    );
  }
}

// PATCH /api/v1/settings/payroll - Update payroll settings
export async function PATCH(req: NextRequest) {
  try {
    const auth = getAuthContext(req);
    const perm = checkPermissions(auth, ['SUPER_ADMIN', 'ADMIN']);
    if (!perm.isAllowed) {
      return NextResponse.json(
        { success: false, message: perm.message },
        { status: perm.statusCode }
      );
    }

    const body = await req.json();
    const {
      frequency,
      processingDay,
      currency,
      workingDaysPerMonth,
      lopCalculationMode,
      overtimeRateMultiplier,
      pfContributionPercent,
      esiContributionPercent,
      requireApproval,
      taxDeductionEnabled,
      payslipNote,
    } = body;

    const pf = Number(pfContributionPercent);
    if (isNaN(pf) || pf < 0 || pf > 50) {
      return NextResponse.json(
        { success: false, message: 'PF contribution percentage must be between 0% and 50%.' },
        { status: 400 }
      );
    }

    const esi = Number(esiContributionPercent);
    if (isNaN(esi) || esi < 0 || esi > 20) {
      return NextResponse.json(
        { success: false, message: 'ESI contribution percentage must be between 0% and 20%.' },
        { status: 400 }
      );
    }

    const otMult = Number(overtimeRateMultiplier);
    if (isNaN(otMult) || otMult < 1.0 || otMult > 5.0) {
      return NextResponse.json(
        { success: false, message: 'Overtime multiplier must be between 1.0 and 5.0.' },
        { status: 400 }
      );
    }

    const { db } = await connectToDatabase();
    const orgId = auth.organizationId;
    const now = new Date();

    const updatedPayrollSettings = {
      frequency: frequency || 'MONTHLY',
      processingDay: Number(processingDay) || 1,
      currency: currency || 'INR',
      workingDaysPerMonth: workingDaysPerMonth === 'ACTUAL' ? 'ACTUAL' : Number(workingDaysPerMonth) || 26,
      lopCalculationMode: lopCalculationMode || 'PRO_RATA_WORKING',
      overtimeRateMultiplier: otMult,
      pfContributionPercent: pf,
      esiContributionPercent: esi,
      requireApproval: Boolean(requireApproval),
      taxDeductionEnabled: Boolean(taxDeductionEnabled),
      payslipNote: payslipNote ? String(payslipNote).trim() : '',
      updatedAt: now,
    };

    await db.collection('organization_settings').updateOne(
      { organizationId: orgId },
      {
        $set: {
          payroll: updatedPayrollSettings,
          updatedAt: now,
        },
      },
      { upsert: true }
    );

    await logAuditEvent(req, 'UPDATE_PAYROLL_SETTINGS', {
      details: { organizationId: orgId, settings: updatedPayrollSettings },
    });

    return NextResponse.json({
      success: true,
      message: 'Payroll settings updated successfully. Future payroll runs will apply these configurations.',
      data: updatedPayrollSettings,
    });
  } catch (error: any) {
    console.error('Error in PATCH /api/v1/settings/payroll:', error);
    return NextResponse.json(
      { success: false, message: error.message || 'Failed to update payroll settings.' },
      { status: 500 }
    );
  }
}
